### ISSUE TITLE
Should anything else be able to go in the Disposal?

### ISSUE THREAD

**Issue by jcourt325** [project-viable/viable-virtual-lab#122]
At the very least we should be able to put Containers' contents in there

**Comment by ksnmoore** [comment]
Things to go into disposal:

- Tips (already do), but can we change the text? When the pipette with a tip is over the biohazard container, the text asks whether the user wants to dispose of the pipette rather than the tip
- Agarose from scoopula or flask
- TAE from graduated cylinder or flask
- Gel from flask or mold
